### ISSUE TITLE
Docker pulls don't work from non-tls protected docker registry 

### ISSUE THREAD

**Issue by naterini** [singularityware/singularityware.github.io#117]
We have a private registry that is setup with unencrypted http service:

nate@test:~> /ncar/opt/singularity/2.3.1/bin/singularity shell docker://test-registry/library/ubuntu:latest
ERROR Unrecognized authentication challenge, exiting.

nate@test:~> curl  http://docker-cache.ssg.ucar.edu/v2/; echo
{}

How do we set the full path for the url for the docker repo?

**Comment by vsoch** [comment]
hey would you mind putting this on the main singularity repo? This repo is for the docs. I'm in meetings for a bit but will be able to help you later. Thanks!

**Comment by naterini** [comment]
Found work around: export SINGULARITY_NOHTTPS=yes

Could that be added to the docs?

**Comment by vsoch** [comment]
so glad that worked! It was added for this exact reason. I will definitely add better docs for it.

**Comment by naterini** [comment]
Had to also upgrade to 2.3.2 to get it working which confused the issue.

Thanks
--Nate

**Comment by vsoch** [comment]
hey @nateucar ! This isn't merged, but I did the brunt of writing to add an entire page (linked from main build) about environment variables you can control for situations like these:

https://github.com/singularityware/singularityware.github.io/pull/115/files#diff-bef4ac71470261efb17dff4700013145

We should get this merged in and added to coincide with 2.4 release.

**Comment by naterini** [comment]
Thanks!
