### ISSUE TITLE
Add entire page for bootstrap environment options

### ISSUE THREAD

**Issue by vsoch** [singularityware/singularityware.github.io#119]

**Comment by vsoch** [comment]
This will be closed with #115

**Comment by GodloveD** [comment]
You did this right?

**Comment by vsoch** [comment]
Yep! This is the build-environment.md file with all the cache and Docker nonsense. Thanks for checking! (And I hope you are getting lots of satisfaction  with closing issues - you worked hard and deserve it! :D

**Comment by GodloveD** [comment]
Yes.  Closing issues is fun.  We have all worked hard.  Quick minute to catch our breath and then it's time to work hard again.  😺
