### ISSUE TITLE
Order should be "Build an Image" "Container Recipes" "Singularity Flow" in the user guide

### ISSUE THREAD

**Issue by GodloveD** [singularityware/singularityware.github.io#122]
I think it is probably a good idea that a user learns in the following order:

1. Build an Image (since the build command may or may not be used in conjunction with a Recipe)
2. Container Recipes (since that is like advanced usage for the build command)
3. Singularity Flow (since that is like best practices for using both the of the two above)

I tried rearranging the order in `_data/sidebars/user_docs.yml` but the changes were not reflected in the Jekyll build.  @vsoch can you please take a look at this?

**Comment by vsoch** [comment]
you got it @GodloveD !

**Comment by GodloveD** [comment]
Thanks!
