### ISSUE TITLE
export commands still outdated

### ISSUE THREAD

**Issue by olifre** [singularityware/singularityware.github.io#137]
The export commands (now named `image.export`) are still outdated. 

For example, in:
http://singularity.lbl.gov/docs-export
I find that the recommended way to compress images would be:
```
singularity export container.img | gzip -9 > container.img.gz
```
Apart from the fact that "export" is not even a supported command anymore (and I think the Release Notes did not even mention the rename? That's ugly, that's a backwards incompatible change, please announce that!), if I run:
```
singularity image.export container.img | gzip -9 > container.img.gz
```
on a SquashFS-container the result will commonly be a *larger* container.img.gz file, which is then also actually a "tar.gz" file.

**Comment by vsoch** [comment]
hey @olifre ! I updated the docs to specify image.export, and you are right about the larger file! I'll add a note that this command is typically intended for the older format.

**Comment by vsoch** [comment]
Is this fix suitable? If you have a suggestion for a better description, definitely go for it!

http://singularity.lbl.gov/docs-export

**Comment by olifre** [comment]
> Is this fix suitable? If you have a suggestion for a better description, definitely go for it!

I believe it's good!
I think I would still change the last command, though, to read:
```
singularity image.export container.img | gzip -9 > container.img.tar.gz
```
to clarify that the resulting file actually is a compressed tarball (maybe the drop the `.img` part also for that, but that's a matter of taste).

**Comment by vsoch** [comment]
done! Should render in 30 seconds to a minute. Depending on if the Github robots are having an afternoon snack.

**Comment by vsoch** [comment]
@olifre if this looks ok now feel free to close the issue.

**Comment by olifre** [comment]
Yep, let's close that :-)
