### ISSUE TITLE
squashfs-tools installation requirement

### ISSUE THREAD

**Issue by johnbradley** [singularityware/singularityware.github.io#166]
I do not see any documentation about needing squashfs-tools in the installation instructions http://singularity.lbl.gov/install-linux. It would be nice to mention this even if it is an optional module.
There is an error raised if squashfs-tools isn't installed and you attempt to pull a docker image: https://github.com/singularityware/singularity/issues/1078

Thanks.

**Comment by vsoch** [comment]
We could definitely add that! I think my worry is that the list of actual dependencies would get out of sync with the documentation (this seems to always happen) but do you think it's worth it anyway? If the admin / user is going to install, arguably he/she will hit the missing dependencies during configuration. Do you think it's better to read/see the list in advance? If so we can definitely add something!

**Comment by johnbradley** [comment]
Thanks for the quick reply @vsoch.

I agree that an outdated list of requirements wouldn't be helpful. I was upgrading from 2.3.1 to 2.4.2 and didn't know this was a new requirement. The configure/make/make install process didn't error. I did some brief testing and everything seemed to be working fine until I tried the `pull` command against dockerhub. Had I not tried this particular command/argument I wouldn't have known I missed a step in setup. 
I am using Redhat so configure/make/make install might be different under other OSs.

**Comment by vsoch** [comment]
I think probably we should open an issue with the install itself, I'm thinking what happens for (most of the world) that doesn't read docs and hits the same issue still? I can write this up and ping you!

**Comment by vsoch** [comment]
hey @johnbradley I added a note here http://singularity.lbl.gov/install-linux and also to the admin docs, does this address your issue?

**Comment by johnbradley** [comment]
Thanks @vsoch. This resolves my issue.
