### ISSUE TITLE
Numbering in welcome section

### ISSUE THREAD

**Issue by verdurin** [singularityware/singularityware.github.io#18]
The numbering of the paragraphs in the section [http://singularity.lbl.gov/user-guide#welcome-to-singularity](http://singularity.lbl.gov/user-guide#welcome-to-singularity) needs to be fixed so that they're not all the same.

**Comment by vsoch** [comment]
Take a look now - is the issue fixed?

**Comment by verdurin** [comment]
Yes, that looks much nice now, thanks.
