### ISSUE TITLE
Missing link in 2.5 & 2.6 user documentation

### ISSUE THREAD

**Issue by GodloveD** [singularityware/singularityware.github.io#202]
Just linking this issue here in the docs section so that it will be seen.

@devprincess 

https://github.com/singularityware/singularity/issues/1919

**Comment by jscook2345** [comment]
I fixed this in the singularity-userdocs repo.

https://github.com/singularityware/singularity-userdocs/pulls

**Comment by jchavezlavalle** [comment]
@GodloveD @jscook2345 thanks guys, this change has been merged :tada:
