### ISSUE TITLE
[idea]: graphical representation of the Singularity workflow

### ISSUE THREAD

**Issue by chrisgorgo** [singularityware/singularityware.github.io#31]
I like[ this figure made for Shifter](https://tin6150.github.io/psg/blogger_container_hpc.html#shifter_workflow). It would be very useful for new users to see something like this for Singularity (could be even on the landing page). Especially explaining different ways of making Singularity images (bootstrap from spec (linux), bootstrap from docker hub (linux), docker2singularity (linux, mac, windows)).

**Comment by vsoch** [comment]
Yes, this is a great idea! Definitely will get something in the works! Do you have a project / paper that you are looking to put the figure in, in other words, a deadline?

**Comment by chrisgorgo** [comment]
Oh I don't need it personally - I just thought it would be beneficial for the Singularity project.

**Comment by vsoch** [comment]
yes it would! Thanks :O)

**Comment by vsoch** [comment]
This is done, and added to 2.3, and will be pushed (and closed) with the 2.3 release milestone https://github.com/singularityware/singularityware.github.io/milestone/1

**Comment by chrisgorgo** [comment]
Awesome! This will be so useful for new users. Do you have a link?

**Comment by vsoch** [comment]
It's coming out in the Singularity paper proper, so I'd like to wait on sharing it until that, or when the docs are released, whichever comes first!.

**Comment by vsoch** [comment]
hey @chrisfilo, wish granted! The figure included in our paper is now live with the 2.3 docs, front page. Closing issue!

**Comment by vsoch** [comment]
and I'll put here, in case the site farts and dies someday:

![image](https://cloud.githubusercontent.com/assets/814322/26659936/a73b1b54-4642-11e7-824b-d91d1d6a6545.png)

because Github will live on :)

**Comment by chrisgorgo** [comment]
Thanks - looks great!

**Comment by vsoch** [comment]
:grin:
