### ISSUE TITLE
Trying to replicate docker / tensorflow example

### ISSUE THREAD

**Issue by chrisreidy** [singularityware/singularityware.github.io#33]
Hi
I am trying to replicate this:
http://singularity.lbl.gov/docs-docker
because I have use cases for docker and separate use cases for tensorflow.
Whether I use singularity bootstrap, exec or import against docker://tensorflow/tensorflow:latest
I get:
Error getting tags using url https://registry-1.docker.io/v2/tensorflow/tensorflow/tags/list
On my Mac Docker app, I can run "docker pull tensorflow/tensorflow" successfully

Thanks for your help

**Comment by vsoch** [comment]
What version of singularity are you using? We had a bug in an older version that would produce this. Could you install the current master and try again?

**Comment by chrisreidy** [comment]
I am using 2.2.  The tarball is dated October 24

**Comment by vsoch** [comment]
I would install the version from master and try again - the bug that was fixed was in November I believe!

**Comment by chrisreidy** [comment]
I tried installing the latest from git and get this error:
singularity create -s 4000 docker-tf.img
Creating a new image with a maximum size of 4000MiB...
Executing image create helper
/cm/shared/apps/singularity/2.2/libexec/singularity/simage: symbol lookup error: /cm/shared/apps/singularity/2.2/libexec/singularity/simage: undefined symbol: singularity_image_bind

So I reinstalled the 2.2 version and the 'create' functioned normally

**Comment by vsoch** [comment]
Hey @chrisreidy could you post this on the [singularity issues board](https://github.com/singularityware/singularity/issues)? This one is for the docs site, and the other board will get direct attention of all developers.

**Comment by chrisreidy** [comment]
Reposted to Issues board

**Comment by vsoch** [comment]
Thank you!

**Comment by vsoch** [comment]
https://github.com/singularityware/singularity/issues/393
