### ISSUE TITLE
update info wrt singularity-hub

### ISSUE THREAD

**Issue by serious-steve** [singularityware/singularityware.github.io#42]
In the 'Quick Links' section there's a dead link in https://github.com/singularityware/singularity-hub.

Files affected:

_data/topnav.yml (Remove/Replace external link to singularity-hub)
_site/docs-hpc.html (Info about what is singularity, needs update maybe, or removal?)

**Comment by vsoch** [comment]
Thanks for the catch! The code base has been made private, in case there are security issues. The singularity hub release should be in the next couple of months, so for now we can remove the link to the repo.

**Comment by serious-steve** [comment]
Please remove the leading `www` in the link. It resolves but results in a certificate mismatch error in firefox. The direct link https://singularity-hub.org/faq has no problem with the certificate though.
