### ISSUE TITLE
update vagrant box and docs for singularity 2.3

### ISSUE THREAD

**Issue by vsoch** [singularityware/singularityware.github.io#82]
hey @alaindomissy - 2.3 is released! Do you want to create the new bento box for it, and then I would be happy to test and update the docs? :bento:

**Comment by alaindomissy** [comment]
I just did :-) Please test it and let me know. Thanks.
Also I made a PR as we were missing a "vagrant up" step

**Comment by vsoch** [comment]
okay all tested, and updated! --> http://singularity.lbl.gov/install-mac Thanks for your speedy work!
