### ISSUE TITLE
add debian repo (with instructions) as an install option

### ISSUE THREAD

**Issue by vsoch** [singularityware/singularityware.github.io#87]
hey @yarikoptic if you are going to be maintaining https://anonscm.debian.org/gitweb/?p=collab-maint/singularity-container.git for each release, could you dump out some text here for how a "I've never done this before" user can use your resource to install Singularity? I'd like to add a page to the install docs on how to do this, because we have many docs for "how to roll your own" but I think it should be the case that we give a resource so the user doesn't have to. Thanks!

**Comment by yarikoptic** [comment]
In short I would say: singularity is available on Debian (and Ubuntu) systems starting with Debian stretch (and Ubuntu 16.10 yakkety) release as a package singularity-container. So you just need to `apt-get install singularity-container`. If you need a backport build of the recent release of singularity on those or older releases of Debian and Ubuntu, please enable NeuroDebian repository following instructions on http://neuro.debian.net .

**Comment by vsoch** [comment]
ok all set, thanks @yarikoptic !

http://singularity.lbl.gov/install-linux#debianubuntu-package

**Comment by yarikoptic** [comment]
Cool
Spotted typo. continue worker

**Comment by vsoch** [comment]
typo? What typo?   .... **whistles casually, kicks something under a rug, and strolls down the street for a coffee and pastry**

**Comment by yarikoptic** [comment]
continue worker -> continue working
