### ISSUE TITLE
add development section / 2.4 branch

### ISSUE THREAD

**Issue by vsoch** [singularityware/singularityware.github.io#92]
there is enough thinking / development going on to warrant a new section. @gmkurtzer should we have a section live on the site, or put again into some docs/2.4 branch? This (so far) will include checks, container instances, and apps.

**Comment by gmkurtzer** [comment]
I think the branch is enough, but I'm open to a different section. another way to handle it is how RH deals with docs (Which is actually very good). They version their URLs/paths like:

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/

And from that we know it applies to RHEL7. The RHEL6 guide is also live and available at the corresponding URL.

**Comment by vsoch** [comment]
okay, we will have a similar but simpler schema, an archive that has all docs of past:

 - http://singularity.lbl.gov/archive/

and then any particular version has format:

 - http://singularity.lbl.gov/archive/docs/v2-2
 - http://singularity.lbl.gov/archive/docs/v2-3

And they reference the branch and we will still link to the tags / branches. These serve as a quicker / nicer to look at way to find some old thing.

**Comment by vsoch** [comment]
docs for 2.4 added, started so far are for checks and container instances:

https://github.com/singularityware/singularityware.github.io/tree/docs/2.4

**Comment by gmkurtzer** [comment]
WAHOOO!
